### ISSUE TITLE
File handles leak when using Bottle.mount() and uWSGI

### ISSUE THREAD

**Issue by trvrm** [bottlepy/bottle#703]
This is a pretty subtle bug; and I've produced a detailed write-up at http://trvrm.github.io/seriously-subtle-bug.html.

In brief, using `static_file` in routes served via `Bottle.mount()` in a uWSGI environment causes file handles to leak.  The underlying reason is that https://github.com/bottlepy/bottle/blob/master/bottle.py#L914 is called twice, `_cast()` is called recursively when used with bottle.mount().

This isn't a problem with WSGIRefServer, but under uWSGI 

`request.environ['wsgi.file_wrapper']` is mapped to `py_uwsgi_sendfile`

(https://github.com/unbit/uwsgi/blob/ed2ca5d33325dc925f6fc5558d0b817447327049/plugins/python/wsgi_handlers.c#L463)

which appears to increment the refcount too many times if it's called more than once.

I don't know if this is a bug with Bottle, uWSGI, or with the WSGI standard, because I'm not sure what `wsgi.file_wrapper` is meant to achieve.

**Comment by defnull** [comment]
Ahh I see. Bottle wraps a wsgi.file_wrapper returned by a mounted app again in a file_wrapper because it looks like a file to the other app. Yes, thats a bug and should be fixed.

**Comment by defnull** [comment]
Fixed in e456b4.

**Comment by trvrm** [comment]
Regretfully I'm still getting the resource leak with this version of Bottle, but only when running under UWSGI.

This is the app I'm testing:

```
import os,psutil, sys, uuid
import bottle_post as bottle

app=bottle.Bottle()           
bottle.debug(True)       
template=bottle.SimpleTemplate("""
Refresh this page a few times and see if the open file count goes up.
<pre>

There are {{len(files)}} open files:

{{'\\n'.join(files)}}

Bottle: {{f}}
Version: {{version}}
</pre>
 
<img src="cat?x={{u}}">
<!-- Use a unique ID to bypass browser caching.-->
    """ )
    
@app.get('/info')
def info():     
    ''' Hitting this route multiple times causes the number of open files to go up'''
    process     = psutil.Process(os.getpid())                          
    files       = [f.path for f in process.get_open_files()]
    version     = sys.version
    f           = bottle.__file__
    u           = str(uuid.uuid4())
    
    return template .render(**locals())
 
@app.get('/cat')
def getCatPicture():
    return bottle.static_file('cat.jpg', '.')

application=bottle.Bottle()             
application.mount("/diagnose", app)```

**Comment by trvrm** [comment]
Ah, no, my mistake.  

Changing:
```application.mount("/diagnose", app)``` 
to
```application.mount("/diagnose/", app)```

seems to have fixed it.  I didn't catch that deprecation warning the first time.
