### ISSUE TITLE
ResourceWarning unclosed <socket.socket>

### ISSUE THREAD

**Issue by Phyks** [bottlepy/bottle#814]
Hi,

When quitting a Bottle app using ^C and the built-in webserver, I get this message in the console:
```
/bottle.py:3119: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8080)>
```

Then, it hangs, and I have to ^C a second times to exit.

It should not be a big deal, but I never saw it before. Is it due to some recent changes? Thanks!

**Comment by defnull** [comment]
Which Python an Bottle version?

**Comment by Phyks** [comment]
Python 3.5.1. Bottle 0.12.9 installed from `pip`.

**Comment by Phyks** [comment]
Let me know if I can be useful in any way :)

**Comment by tprk77** [comment]
Me too! Xubuntu 16.04 x86_64, `virtualenv`, Python 3.5.2, Bottle 0.12.9 from `pip`.

**Comment by katsar0v** [comment]
Same here still valid

**Comment by Lisias** [comment]
I confirm this is still a problem.

```
Python 3.5.2 (default, Dec 15 2016, 16:12:17)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bottle
>>> bottle.__version__
'0.13-dev'
>>>
```

And later, after hitting CTRL-C to stop a program:
```
sys:1: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=2049, proto=0>
/home/srv/python/3.4/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty
sys:1: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_UNIX, type=2049, proto=0>
```

**Comment by ahxxm** [comment]
+1

python3.5.2 and 3.6.1rc1, bottle 0.12.13, paste 2.0.3

**Comment by defnull** [comment]
I still cannot reproduce this error. I do get the 'unclosed resource' warning, but the process does not hang.

The resource warning is caused by the stdlib wsgi server not closing the socket after a ``KeyboardInterrupt``. It does not do much harm, since sockets are closed on process shutdown anyway, it is just annoying. Even after calling shutdown() on the server explicitly the warning remains. I don't see an easy way to prevent this warning other than patching the wsgiref server in the stdlib or waiting for a bugfix there.

**Comment by gfemec** [comment]
For what it's worth, fe7285893505f949b48e0f873d44c5386917b7ae (part of 0.13 development) seems to address the unclosed socket and prevents the warning for me.

**Comment by robvdl** [comment]
Yes but this was fixed 5 years ago (2014) and we're still waiting for it to be released which isn't very good.

You get the socket close warning on python 3 and bottle 0.12, I'm trying to port a project over to python 3 before the python 2 apocalypse sets in :) but bottle 0.13 is still in dev, can't this fix be backported to 0.12?

**Comment by p0lm** [comment]
Still bumping into this.

**Comment by chrism** [comment]
Getting this message too.

If anyone knows of a workaround much appreciated.

**Comment by sbargy** [comment]
Yep, I'm getting this warning, too.  Hadn't seen it before, just cropped up in the last couple days.  I'm investigating further to see what changed.

**Comment by robvdl** [comment]
@sbargy interesting I always thought it was running on Python 3 that did this. Have you always been on python3 or have you only recently upgraded to python3?

**Comment by franz-simonetti** [comment]
Very similar problem: when quitting a Bottle app using ^C and the built-in webserver, I get this message in the console:
`sys:1: ResourceWarning: unclosed <socket.socket fd=544, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8080)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback`
However it does not hangs, I get the command prompt directly.
Python 3.8.2, Bottle v0.12.18 on Windows 10 Pro 1909 build 18363.778

**Comment by Nozavi** [comment]
Experiencing the same issue
Python 3.7, Bottle v0.12.18, Windows 10 Pro 1909 build 18363.836

bottle.py:3139: ResourceWarning: unclosed <socket.socket fd=752, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8080)>

**Comment by sbargy** [comment]
@robvdl I've been running Python 3 on this code base since it was started.

**Comment by robvdl** [comment]
Ok it might not just be Python 3 but be something we're doing but it's irrelevant because it's happening to a LOT of people, not just me and it's not getting resolved by backporting the 0.13 fix (it should be). Bottle.py releases come out at a snails pace we've been waiting for about 5 years for 0.13, I'm trying to not be negative but it's hard, how long until 0.13 is not in beta? it's getting a bit rediculous.

Our codebase did not come up with the unclosed socket error on Python 2, but did do it on Python 3 which made me conclude it was that at the time.

The only reason we are still using bottle.py is because we're stuck with it on a legacy project, but the bottle release procedure is really slow. Bottle 0.12 came out in 2014 it's now 6 years later and 0.13 is still not out.

**Comment by robvdl** [comment]
@sbargy did you try it with autoreloading (hot reload) that triggers it. Make a code change, bottle restarts and says unclosed socket.

**Comment by x-yuri** [comment]
Debian 10 "buster", Python 3.8.3, `bottle==0.12.18`. It doesn't hang. The warning is only displayed in debug mode. #648 resolves the issue (for `wsgiref`):

```diff
--- /usr/local/bin/bottle.py	2020-07-05 12:40:20.499112052 +0000
+++ /usr/local/bin/bottle.py	2020-07-05 12:40:44.522967162 +0000
@@ -2787,7 +2787,11 @@
                     address_family = socket.AF_INET6
 
         srv = make_server(self.host, self.port, app, server_cls, handler_cls)
-        srv.serve_forever()
+        try:
+            srv.serve_forever()
+        except KeyboardInterrupt:
+            srv.server_close() # Prevent ResourceWarning: unclosed socket
+            raise
 
 
 class CherryPyServer(ServerAdapter):
```

Are you sure it hangs? Maybe just outputs the warning over the prompt?

**Comment by satisfaya** [comment]
GUYS! This problem is nothing to worry about. Make these changes to fix the problem:
`from bottle import Bottle`
then set
`app = Bottle()`
finally change the run command to:
`run(app, host='localhost', port=8080)`

**Comment by qcda1** [comment]
Humm. I still have this message and I would need to know how to close the socket when the  program exit the run statement. In my case, I would like to restart the web server (run statement) by sending SIGINT to the running process. By doing this, the program bomb when run is launch again as follow:

Here is the terminal session:
daniel@MPDeb64:~/devel/midnite$ python 'midnitenp (copie).py'
Step Start of program, duration=0.00ms
Step run(host... statement, duration=0.06ms
Bottle v0.12.19 server starting up (using WSGIRefServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

127.0.0.1 - - [17/Jan/2023 11:31:47] "GET /mesures1 HTTP/1.1" 404 736
**OK received SIGINT and exited from run, waiting 10 seconds...**
Step Start of program, duration=0.01ms
Step run(host... statement, duration=0.08ms
Bottle v0.12.19 server starting up (using WSGIRefServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "midnitenp (copie).py", line 113, in <module>
    run(app, host='localhost', port=8080)
  File "/home/daniel/.local/lib/python3.7/site-packages/bottle.py", line 3137, in run
    server.run(app)
  File "/home/daniel/.local/lib/python3.7/site-packages/bottle.py", line 2789, in run
    srv = make_server(self.host, self.port, app, server_cls, handler_cls)
  File "/usr/lib/python3.7/wsgiref/simple_server.py", line 153, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
**OSError: [Errno 98] Address already in use**
/usr/local/lib/python3.7/dist-packages/matplotlib/_pylab_helpers.py:92: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8080)>
  gc.collect(1)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
daniel@MPDeb64:~/devel/midnite$ 

Here is the code:
# MAIN PROGRAM
while True:
    ts = time.time()
    stamp("Start of program")    
    stamp("run(host... statement")
    app = Bottle()
    debug(True)
    run(app, host='localhost', port=8080)
    print("OK received SIGINT and exited from run, waiting 10 seconds...")
    sleep(10)
    
print("Program end.")



Thanks for the help!
Regards,
Daniel.

**Comment by qcda1** [comment]
Humm. I still have this message and I would need to know how to close the socket when the  program exit the run statement. In my case, I would like to restart the web server (run statement) by sending SIGINT to the running process. By doing this, the program bomb when run is launch again as follow:

Here is the terminal session:
daniel@MPDeb64:~/devel/midnite$ python 'midnitenp (copie).py'
Step Start of program, duration=0.00ms
Step run(host... statement, duration=0.06ms
Bottle v0.12.19 server starting up (using WSGIRefServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

127.0.0.1 - - [17/Jan/2023 11:31:47] "GET /mesures1 HTTP/1.1" 404 736
**OK received SIGINT and exited from run, waiting 10 seconds...**
Step Start of program, duration=0.01ms
Step run(host... statement, duration=0.08ms
Bottle v0.12.19 server starting up (using WSGIRefServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "midnitenp (copie).py", line 113, in <module>
    run(app, host='localhost', port=8080)
  File "/home/daniel/.local/lib/python3.7/site-packages/bottle.py", line 3137, in run
    server.run(app)
  File "/home/daniel/.local/lib/python3.7/site-packages/bottle.py", line 2789, in run
    srv = make_server(self.host, self.port, app, server_cls, handler_cls)
  File "/usr/lib/python3.7/wsgiref/simple_server.py", line 153, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
**OSError: [Errno 98] Address already in use**
/usr/local/lib/python3.7/dist-packages/matplotlib/_pylab_helpers.py:92: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8080)>
  gc.collect(1)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
daniel@MPDeb64:~/devel/midnite$ 

Here is the code:
# MAIN PROGRAM
while True:
    ts = time.time()
    stamp("Start of program")    
    stamp("run(host... statement")
    app = Bottle()
    debug(True)
    run(app, host='localhost', port=8080)
    print("OK received SIGINT and exited from run, waiting 10 seconds...")
    sleep(10)
    
print("Program end.")



Thanks for the help!
Regards,
Daniel.

**Comment by defnull** [comment]
This is fixed in `master`, but not in `0.12` yet. The `wsgitef` implementation does not properly clean up the socket server on SIGINT, so you could use a different server adapter that handles interrupts better, or skip the server adapter and the `run()` method and instead setup `wsgiref.simple_server` yourself. Bottles server-adapters are only a suggestion, you can simply run Bottle with `wsgiref` as suggested by https://github.com/bottlepy/bottle/issues/814#issuecomment-653884603

**Comment by XLTechie** [comment]
Should this be closed? It's still happening to me, on Bottle 0.12.19, Python 3.10.12. These are latest on Ubuntu LTS, unfortunately.
But I gather it has been fixed in 0.13 though, so maybe it will stop happening eventually?
